project:
  type: website
  output-dir: docs

website:
  title: "Sumitra Ghalley â€“ MBA Portfolio"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Contact"
        href: contact.qmd

fformat:
  html:
    theme: cosmo
    css: styles.css
    

